name: gebu_client
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_datetime_picker: ^1.5.1
  flutter_native_splash: ^2.1.1
  get: 4.6.1
  google_fonts: 2.3.1
  google_nav_bar: ^5.0.5
  persistent_bottom_nav_bar: ^4.0.2
  flutter_screenutil: ^5.3.1
  table_calendar: ^3.0.4
  twilio_flutter: ^0.0.9
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  background_image: "assets/images/splashscreen.png"
  fullscreen: true
